repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black
        name: Black Code Formatter
        entry: python scripts/run_black.sh
        language: python
        types: [python]
        args: [--config=pyproject.toml]

      - id: isort
        name: Isort Import Sorter
        entry: python scripts/run_isort.sh
        language: python
        types: [python]
        args: [--settings-path=pyproject.toml]

      - id: flake8
        name: Flake8 Linter
        entry: python scripts/run_flake8.sh
        language: python
        types: [python]

      - id: mypy
        name: Mypy Type Checker
        entry: python scripts/run_mypy.sh
        language: python
        types: [python]
        # Exclude architecture-checks from mypy for opal-dev-tools itself
        exclude: ^architecture-checks/

      - id: bandit
        name: Bandit Security Linter
        entry: python scripts/run_bandit.sh
        language: python
        types: [python]
        args: [-r, .]

      - id: pytest
        name: Run Unit Tests
        entry: python scripts/run_pytest.sh
        language: python
        pass_filenames: false
        types: [python]
        # Disable pytest for opal-dev-tools itself as it doesn't have unit tests
        enabled: false

      - id: eslint
        name: ESLint Linter
        entry: scripts/run_eslint.sh
        language: system
        types: [javascript]

      - id: prettier
        name: Prettier Code Formatter
        entry: scripts/run_prettier.sh
        language: system
        types: [javascript, css, html, json, markdown, yaml]

      - id: check-dependencies
        name: Check Architectural Dependencies
        entry: python architecture-checks/check_dependencies.py
        language: python
        additional_dependencies: ["toml"]
        pass_filenames: false
        types: [python]

      - id: check-imports
        name: Check Architectural Imports
        entry: python architecture-checks/check_imports.py
        language: python
        pass_filenames: false
        types: [python]

      - id: check-structure
        name: Check Architectural Structure
        entry: python architecture-checks/check_structure.py
        language: python
        pass_filenames: false
        types: [python]
        # Exclude check-structure for opal-dev-tools itself
        exclude: |
          (?x)^(
              README\.md|
              \.pre-commit-config\.yaml|
              \.pre-commit-hooks\.yaml|
              architecture-checks/.*|
              scripts/.*|
          )$
