# Python Hooks
- id: black
  name: Black Code Formatter
  entry: ./scripts/run_black.sh
  language: system
  types: [python]
  args: [--config=pyproject.toml] # Assuming black config is in pyproject.toml

- id: isort
  name: Isort Import Sorter
  entry: ./scripts/run_isort.sh
  language: system
  types: [python]
  args: [--settings-path=pyproject.toml] # Assuming isort config is in pyproject.toml

- id: flake8
  name: Flake8 Linter
  entry: ./scripts/run_flake8.sh
  language: system
  types: [python]

- id: mypy
  name: Mypy Type Checker
  entry: ./scripts/run_mypy.sh
  language: system
  types: [python]
  # Mypy often needs a config file (mypy.ini or pyproject.toml)
  # args: [--config-file=mypy.ini]

- id: bandit
  name: Bandit Security Linter
  entry: ./scripts/run_bandit.sh
  language: system
  types: [python]
  args: [-r, .] # Run recursively on all files

- id: pytest
  name: Run Unit Tests
  entry: ./scripts/run_pytest.sh
  language: system
  pass_filenames: false # Run tests on all files, not just staged ones
  types: [python]

# JavaScript/TypeScript Hooks
- id: eslint
  name: ESLint Linter
  entry: ./scripts/run_eslint.sh
  language: system
  types: [javascript]

- id: prettier
  name: Prettier Code Formatter
  entry: ./scripts/run_prettier.sh
  language: system
  types: [javascript, css, html, json, markdown, yaml]

# OpalSuite Architectural Checks (from architecture-checks directory)
- id: check-dependencies
  name: Check Architectural Dependencies
  entry: python architecture-checks/check_dependencies.py
  language: system
  pass_filenames: false
  types: [python]

- id: check-imports
  name: Check Architectural Imports
  entry: python architecture-checks/check_imports.py
  language: system
  pass_filenames: false
  types: [python]

- id: check-structure
  name: Check Architectural Structure
  entry: python architecture-checks/check_structure.py
  language: system
  pass_filenames: false
  types: [python]
