repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        exclude: ^architecture-checks/ # Exclude architecture-checks directory

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "."]
        additional_dependencies: ["pbr"] # Add pbr as a dependency

  # JavaScript/TypeScript linters (assuming Node.js projects)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier

  # OpalSuite Architectural Checks (from this repository itself)
  - repo: local
    hooks:
      - id: check-dependencies
        name: Check Architectural Dependencies
        entry: python architecture-checks/check_dependencies.py # Direct path to script
        language: python
        additional_dependencies: ["toml"] # Add toml as a dependency
        pass_filenames: false
      - id: check-imports
        name: Check Architectural Imports
        entry: python architecture-checks/check_imports.py # Direct path to script
        language: python
        pass_filenames: false
      - id: check-structure
        name: Check Architectural Structure
        entry: python architecture-checks/check_structure.py # Direct path to script
        language: python
        pass_filenames: false
        # Exclude check-structure for opal-dev-tools itself as it's a tool repo
        # and doesn't necessarily have gemini.md or scripts folder
        exclude: | # Use a regex to exclude files/directories from this check
          (?x)^( # Start extended regex mode
              README\.md|
              \.pre-commit-config\.yaml|
              architecture-checks/.*|
              # Add other files/dirs to exclude from structure check if needed
          )$
